### ISSUE TITLE
Feature request: akternafive to google maps API

### ISSUE THREAD

**Issue by ippocratis** [Rundiz/personal-maps-timeline#1]
Leaflet or maplibre comes to mind

I understand the looks of the app will no longer be an exact clone but using such alternatives has the advantage of being free and open source.

Thanks

**Comment by ve3** [comment]
It is currently using Leaflet.

**Comment by ippocratis** [comment]
> It is currently using Leaflet.

As per installation instructions I have to edit the details of the config.php file and there is a google maps api entry to fill there 

What do I do with it ?

Commit the line?
Leave it empty?

**Comment by ve3** [comment]
You can leave it empty. It is for use when you want to retrieve place detail from Google Maps data.
https://github.com/Rundiz/personal-maps-timeline/blob/07b2a986e86c5e369a77c1c82e3cc3aa43d38619/retrieve-place-detail.php#L138

Leave it empty and don't call this file -> **retrieve-place-detail.php**. Everything else still working fine.

**Comment by ve3** [comment]
I've updated the code comment about this.
https://github.com/Rundiz/personal-maps-timeline/blob/main/default.config.php
